spring.application.name=inovatech
server.port=8081

#Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/inovatech_db
spring.datasource.username=postgres
spring.datasource.password=12345678

#Atualiza o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

#Exibir no terminal o SQL sendo executado
spring.jpa.show-sql=true

#Informa para não formatar o SQL
spring.jpa.properties.hibernate.format_sql=false

#Configura�oes do Thymeleaf
spring.thymeleaf.cache=false

#Configurações de E-mail (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gl2767359@gmail.com
spring.mail.password=uwzvwihatnyvohtz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com